### ISSUE TITLE
CoilDemo fails to load images

### ISSUE THREAD

**Issue by JacobShipley** [alexstyl/add-coil-multiplatform#1]
When running the sample on desktop, `AsyncImage` fails to load the sample images in `CoilDemo`, throwing  `java.lang.NoClassDefFoundError: io/ktor/utils/io/jvm/nio/WritingKt`:

> 🚨 Failed - https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?q=80&w=3223&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D?q=80&w=1024 - java.lang.NoClassDefFoundError: io/ktor/utils/io/jvm/nio/WritingKt
🚨 Failed - https://images.unsplash.com/photo-1506792006437-256b665541e2?q=80&w=3387&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1024 - java.lang.NoClassDefFoundError: io/ktor/utils/io/jvm/nio/WritingKt
🚨 Failed - https://images.unsplash.com/photo-1502691876148-a84978e59af8?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1024 - java.lang.NoClassDefFoundError: io/ktor/utils/io/jvm/nio/WritingKt
🚨 Failed - https://images.unsplash.com/photo-1485163819542-13adeb5e0068?q=80&w=3387&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1024 - java.lang.NoClassDefFoundError: io/ktor/utils/io/jvm/nio/WritingKt
🚨 Failed - https://images.unsplash.com/photo-1516796181074-bf453fbfa3e6?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1024 - java.lang.NoClassDefFoundError: io/ktor/utils/io/jvm/nio/WritingKt

Steps to reproduce:

1. Pull down copy of repo
2. In Demo.kt, add `.logger(DebugLogger())` to the ImageLoader to enable logging output
3. Run the application (`.\gradlew.bat demo:run`) and note the errors output in console

Tested platforms:

- Windows 11

Tested versions:

- `1.1.0`
- `1.2.0`

**Comment by JacobShipley** [comment]
Amending this with a workaround:

Downgrading ktor from `3.0.0-beta-2` to `3.0.0-beta-1` appears to resolve the issue. Versions beyond `3.0.0-beta-2` including `3.0.0-rc-1` and `3.0.0` are also affected, so `beta-1` appears to be the last compatible version.

**Comment by alexstyl** [comment]
Thanks for the investigation

Will check it and publish an update asap

**Comment by alexstyl** [comment]
Just pushed a fix for this. Try the latest version: `implementation("com.alexstyl:addcoilmultiplatform:3.0.0-rc01")`
