### ISSUE TITLE
Project does not build on Windows with TYPESAFE_PROJECT_ACCESSORS enabled

### ISSUE THREAD

**Issue by JacobShipley** [alexstyl/add-coil-multiplatform#2]
When building on Windows 11, gradle fails to generate the project model:

> org.gradle.api.internal.catalog.GeneratedClassCompilationException: Unable to compile generated sources:
>  - File AddcoilmultiplatformProjectDependency.java, line: 13, class AddCoilMultiplatformProjectDependency is public, should be declared in a file named AddCoilMultiplatformProjectDependency.java

This appears to be related to [open gradle issue 28644](https://github.com/gradle/gradle/issues/28644) and may impact platforms with case-insensitive filesystems (though I have only verified similar symptoms, not necessarily a shared root cause).

Steps to reproduce:

1. Pull down copy of repo
2. Attempt to import or build on Windows 11

Tested platforms:

- Windows 11

Tested versions:

- `1.1.0`
- `1.2.0`

Workaround:

Remove or comment out `enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")` in `settings.gradle.kts`

**Comment by alexstyl** [comment]
I don't have a windows machine so I cannot confirm.

Could you open a PR for this and make sure it works on your machine?

Then I can check if everything is ok on mac and push an update
